package com.example.demoOTP.Config;

import org.springframework.stereotype.Component;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
@Component
public class MD5 {
    public String getMd5(String input){
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    // Driver code
//    public static void main(String args[]) throws NoSuchAlgorithmException{
//        String s = "GeeksForGeeks";
//        String s2 = "ppp.key";
//        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s2));
//    }
//    10609549a85c9fd03bd37b25e9f4622b
//    e39b9c178b2c9be4e99b141d956c6ff6
}
